[project]
name = "sign-language-translator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12,<3.13"
dependencies = [
    "mediapipe>=0.10.14",
    "numpy>=2.3.5",
    "protobuf<=4.25.3",
    "torch>=2.9.1",
    "torchvision>=0.24.1",
]
